version: '3.8'
services:
  mongodb:
    image: "mongo"
    container_name: mongodb_compose
    ports:
      - 27017:27017
    volumes:
      - "mongodb_data:/data/db"
  backend:
    image: backend22
    container_name: backend_compose
    ports:
      - 3000:3000
    depends_on:
      - mongodb
    environment:
      MONGO_URL: "mongodb://mongodb_compose:27017"
volumes:
  mongodb_data: